#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog, FlagType};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out =
        String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    out.push_str(&format!(
        "final class {type_name} {{\n  const {type_name}._();\n\n"
    ));
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "  static const String service = '{}';\n",
            dart_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "  static const String {} = '{}';\n",
            dart_ident(&flag.snake),
            dart_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "  static const String {}Default = '{}';\n",
                dart_ident(&flag.snake),
                dart_escape(default)
            ));
        }
    }
    out.push_str("}\n");
    out
}

pub fn render_runtime(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let values = format!("{type_name}Values");
    let mut out =
        String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    out.push_str("import 'env_io_stub.dart' if (dart.library.io) 'env_io.dart' as platform;\n\n");
    out.push_str(&format!("final class {values} {{\n  const {values}({{"));
    for (index, flag) in catalog.flags.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("required this.{}", dart_ident(&flag.snake)));
    }
    out.push_str("});\n\n");
    for flag in &catalog.flags {
        out.push_str(&format!(
            "  final {} {};\n",
            dart_owned_type(&flag.flag_type, flag.default.is_some()),
            dart_ident(&flag.snake)
        ));
    }
    out.push_str("}\n\n");
    out.push_str("/// Pure: resolve values from an explicit lookup.\n");
    out.push_str(&format!(
        "{values} loadFrom(String? Function(String key) lookup) {{\n  return {values}(\n"
    ));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "    {}: {},\n",
            dart_ident(&flag.snake),
            dart_load_expr(flag)
        ));
    }
    out.push_str("  );\n}\n\n");
    out.push_str("/// Resolve values from a map of env keys.\n");
    out.push_str(&format!(
        "{values} loadFromMap(Map<String, String> env) {{\n  return loadFrom((key) => env[key]);\n}}\n\n"
    ));
    out.push_str("/// Effectful: read the process environment.\n");
    out.push_str(&format!(
        "{values} loadFromOs() {{\n  return loadFromMap(platform.osEnvironment());\n}}\n"
    ));
    out.push_str(DART_NON_EMPTY_HELPER);
    if catalog
        .flags
        .iter()
        .any(|flag| flag.flag_type == FlagType::Bool)
    {
        out.push_str(DART_BOOL_HELPER);
    }
    if catalog
        .flags
        .iter()
        .any(|flag| flag.flag_type == FlagType::Int)
    {
        out.push_str(DART_INT_HELPER);
    }
    if catalog
        .flags
        .iter()
        .any(|flag| flag.flag_type == FlagType::Float)
    {
        out.push_str(DART_DOUBLE_HELPER);
    }
    out.push_str(&crate::generate::overlay::render_dart(catalog));
    out.push_str(&super::checker::render_dart(catalog));
    out.push_str(&render_try_load(&values, catalog));
    out
}

fn render_try_load(values: &str, catalog: &Catalog) -> String {
    let mut out = format!(
        "\n/// Like `loadFrom`, but throws when a required key is missing or empty.\n{values} tryLoadFrom(String? Function(String key) lookup) {{\n  final values = loadFrom(lookup);\n"
    );
    for flag in catalog
        .flags
        .iter()
        .filter(|flag| flag.required && flag.default.is_none())
    {
        out.push_str(&format!(
            "  if (values.{ident} == null) {{\n    throw MissingEnv(name: '{env}', expectedType: '{ty}', examples: {examples});\n  }}\n",
            ident = dart_ident(&flag.snake),
            env = dart_escape(&flag.env),
            ty = flag.flag_type,
            examples = dart_try_examples(flag),
        ));
    }
    out.push_str("  return values;\n}\n\n");
    out.push_str(&format!(
        "{values} tryLoadFromOs() {{\n  return tryLoadFrom((key) => platform.osEnvironment()[key]);\n}}\n"
    ));
    out
}

fn dart_try_examples(flag: &crate::catalog::FlagSpec) -> String {
    format!(
        "[{}]",
        crate::catalog::example_values(flag)
            .iter()
            .map(|value| format!("'{}'", dart_escape(value)))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn dart_owned_type(flag_type: &FlagType, has_default: bool) -> String {
    let inner = match flag_type {
        FlagType::Bool => "bool",
        FlagType::Int => "int",
        FlagType::Float => "double",
        FlagType::Array | FlagType::Map | FlagType::Json | FlagType::String => "String",
    };
    if has_default {
        inner.to_string()
    } else {
        format!("{inner}?")
    }
}

fn dart_load_expr(flag: &crate::catalog::FlagSpec) -> String {
    let key = format!("'{}'", dart_escape(&flag.env));
    match (flag.flag_type, flag.default.as_deref()) {
        (FlagType::Bool, Some(default)) => format!(
            "_parseBool(lookup({key}), {})",
            if default == "true" || default == "1" {
                "true"
            } else {
                "false"
            }
        ),
        (FlagType::Bool, None) => format!(
            "() {{ final raw = lookup({key}); return raw == null ? null : _parseBool(raw, false); }}()"
        ),
        (FlagType::Int, Some(default)) => format!(
            "_parseInt(lookup({key}), {})",
            default.parse::<i64>().unwrap_or(0)
        ),
        (FlagType::Int, None) => format!("int.tryParse(lookup({key}) ?? '')"),
        (FlagType::Float, Some(default)) => format!(
            "_parseDouble(lookup({key}), {})",
            default.parse::<f64>().unwrap_or(0.0)
        ),
        (FlagType::Float, None) => format!("double.tryParse(lookup({key}) ?? '')"),
        (
            FlagType::Array | FlagType::Map | FlagType::Json | FlagType::String,
            Some(default),
        ) => format!("_nonEmpty(lookup({key})) ?? '{}'", dart_escape(default)),
        (FlagType::Array | FlagType::Map | FlagType::Json | FlagType::String, None) => {
            format!("_nonEmpty(lookup({key}))")
        }
    }
}

const DART_NON_EMPTY_HELPER: &str = r#"
String? _nonEmpty(String? raw) {
  final value = raw?.trim();
  if (value == null || value.isEmpty) {
    return null;
  }
  return value;
}
"#;

const DART_BOOL_HELPER: &str = r#"
bool _parseBool(String? raw, bool fallback) {
  switch (raw?.trim()) {
    case '1':
    case 'true':
    case 'TRUE':
    case 'yes':
    case 'YES':
      return true;
    case '0':
    case 'false':
    case 'FALSE':
    case 'no':
    case 'NO':
      return false;
    default:
      return fallback;
  }
}
"#;

const DART_INT_HELPER: &str = r#"
int _parseInt(String? raw, int fallback) {
  return int.tryParse(raw?.trim() ?? '') ?? fallback;
}
"#;

const DART_DOUBLE_HELPER: &str = r#"
double _parseDouble(String? raw, double fallback) {
  return double.tryParse(raw?.trim() ?? '') ?? fallback;
}
"#;

fn dart_ident(snake: &str) -> String {
    let mut parts = snake.split('_');
    let Some(first) = parts.next() else {
        return "value".into();
    };
    let mut out = first.to_string();
    for part in parts {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(head) = chars.next() {
            out.push(head.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn dart_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

pub const ENV_IO: &str = r#"
import 'dart:io';

Map<String, String> osEnvironment() => Platform.environment;

String? readFileUtf8(String path) {
  try {
    return File(path).readAsStringSync();
  } catch (_) {
    return null;
  }
}
"#;

pub const ENV_IO_STUB: &str = r#"
Map<String, String> osEnvironment() => const {};

String? readFileUtf8(String path) => null;
"#;

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn dart_emits_static_const_keys() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("final class SidecarEnv"));
        assert!(source.contains("static const String service = 'vxl-sidecar';"));
        assert!(source.contains("static const String bind = 'VXL_SIDECAR_BIND';"));
        assert!(source.contains("static const String bindDefault = '127.0.0.1:9090';"));
    }

    #[test]
    fn dart_runtime_reads_bind_from_lookup() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = super::render_runtime(&catalog);
        assert!(source.contains("final class SidecarEnvValues"));
        assert!(source.contains("SidecarEnvValues loadFrom"));
        assert!(source.contains("SidecarEnvValues loadFromOs()"));
        assert!(source.contains("lookup('VXL_SIDECAR_BIND')"));
        assert!(source
            .contains("import 'env_io_stub.dart' if (dart.library.io) 'env_io.dart' as platform;"));
        assert!(!source.contains("import 'dart:io';"));
        assert!(source.contains("platform.osEnvironment()"));
        assert!(source.contains("_contractCheckString"));
        assert!(!source.contains("_parseBool"));
        assert!(!source.contains("_parseInt"));
        assert!(!source.contains("_parseDouble"));
        assert!(!source.contains("_contractCheckBool"));
        assert!(!source.contains("_contractCheckInt"));
        assert!(!source.contains("_contractCheckFloat"));
        assert!(!source.contains("_contractCheckJson"));
    }
}
