#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out = String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    out.push_str(&format!("final class {type_name} {{\n  const {type_name}._();\n\n"));
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "  static const String service = '{}';\n",
            dart_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "  static const String {} = '{}';\n",
            dart_ident(&flag.snake),
            dart_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "  static const String {}Default = '{}';\n",
                dart_ident(&flag.snake),
                dart_escape(default)
            ));
        }
    }
    out.push_str("}\n");
    out
}

fn dart_ident(snake: &str) -> String {
    let mut parts = snake.split('_');
    let Some(first) = parts.next() else {
        return "value".into();
    };
    let mut out = first.to_string();
    for part in parts {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(head) = chars.next() {
            out.push(head.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn dart_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn dart_emits_static_const_keys() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("final class SidecarEnv"));
        assert!(source.contains("static const String service = 'vxl-sidecar';"));
        assert!(source.contains("static const String bind = 'VXL_SIDECAR_BIND';"));
        assert!(source.contains("static const String bindDefault = '127.0.0.1:9090';"));
    }
}
