#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out =
        String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "pub const service = \"{}\"\n\n",
            gleam_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "pub const {} = \"{}\"\n",
            flag.snake,
            gleam_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "pub const {}_default = \"{}\"\n",
                flag.snake,
                gleam_escape(default)
            ));
        }
        out.push('\n');
    }
    out.push_str(&format!("pub type {type_name} {{\n  {type_name}(\n"));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "    {}: {},\n",
            flag.snake,
            gleam_value_type(&flag.flag_type)
        ));
    }
    out.push_str("  )\n}\n");
    out
}

pub fn render_runtime(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let values = format!("{type_name}Values");
    let mut out =
        String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    out.push_str("import gleam/option.{type Option, None, Some}\n\n");
    out.push_str(&format!("pub type {values} {{\n  {values}(\n"));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "    {}: {},\n",
            flag.snake,
            gleam_runtime_type(flag.default.is_some())
        ));
    }
    out.push_str("  )\n}\n\n");
    out.push_str("/// Pure: resolve values from an explicit lookup.\n");
    out.push_str(&format!(
        "pub fn load_from(lookup: fn(String) -> Option(String)) -> {values} {{\n  {values}(\n"
    ));
    for flag in &catalog.flags {
        let key = format!("\"{}\"", gleam_escape(&flag.env));
        let expr = match flag.default.as_deref() {
            Some(default) => format!("nonempty_or(lookup({key}), \"{}\")", gleam_escape(default)),
            None => format!("nonempty(lookup({key}))"),
        };
        out.push_str(&format!("    {}: {},\n", flag.snake, expr));
    }
    out.push_str("  )\n}\n\n");
    out.push_str("/// Effectful once the caller supplies process env lookup.\n");
    out.push_str(&format!(
        "pub fn load_from_os(get_env: fn(String) -> Result(String, Nil)) -> {values} {{\n  load_from(fn(key) {{ result_to_option(get_env(key)) }})\n}}\n"
    ));
    out.push_str(GLEAM_RUNTIME_HELPERS);
    out
}

fn gleam_runtime_type(has_default: bool) -> &'static str {
    if has_default {
        "String"
    } else {
        "Option(String)"
    }
}

const GLEAM_RUNTIME_HELPERS: &str = r#"
fn result_to_option(value: Result(String, Nil)) -> Option(String) {
  case value {
    Ok(raw) -> Some(raw)
    Error(_) -> None
  }
}

fn nonempty(raw: Option(String)) -> Option(String) {
  case raw {
    Some("") -> None
    other -> other
  }
}

fn nonempty_or(raw: Option(String), fallback: String) -> String {
  case nonempty(raw) {
    Some(value) -> value
    None -> fallback
  }
}
"#;

fn gleam_value_type(flag_type: &str) -> &'static str {
    match flag_type {
        "bool" => "Bool",
        "int" => "Int",
        "float" => "Float",
        "array" => "List(String)",
        _ => "String",
    }
}

fn gleam_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn gleam_emits_consts_and_type() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("pub const service = \"vxl-sidecar\""));
        assert!(source.contains("pub const bind = \"VXL_SIDECAR_BIND\""));
        assert!(source.contains("pub const bind_default = \"127.0.0.1:9090\""));
        assert!(source.contains("pub type SidecarEnv"));
        assert!(source.contains("bind: String,"));
    }

    #[test]
    fn gleam_runtime_reads_bind_from_lookup() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = super::render_runtime(&catalog);
        assert!(source.contains("pub type SidecarEnvValues"));
        assert!(source.contains("pub fn load_from"));
        assert!(source.contains("pub fn load_from_os"));
        assert!(source.contains("lookup(\"VXL_SIDECAR_BIND\")"));
    }
}
