#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out = String::from("// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n\n");
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "pub const service = \"{}\"\n\n",
            gleam_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "pub const {} = \"{}\"\n",
            flag.snake,
            gleam_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "pub const {}_default = \"{}\"\n",
                flag.snake,
                gleam_escape(default)
            ));
        }
        out.push('\n');
    }
    out.push_str(&format!("pub type {type_name} {{\n  {type_name}(\n"));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "    {}: {},\n",
            flag.snake,
            gleam_value_type(&flag.flag_type)
        ));
    }
    out.push_str("  )\n}\n");
    out
}

fn gleam_value_type(flag_type: &str) -> &'static str {
    match flag_type {
        "bool" => "Bool",
        "int" => "Int",
        "float" => "Float",
        "array" => "List(String)",
        _ => "String",
    }
}

fn gleam_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn gleam_emits_consts_and_type() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("pub const service = \"vxl-sidecar\""));
        assert!(source.contains("pub const bind = \"VXL_SIDECAR_BIND\""));
        assert!(source.contains("pub const bind_default = \"127.0.0.1:9090\""));
        assert!(source.contains("pub type SidecarEnv"));
        assert!(source.contains("bind: String,"));
    }
}
