#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out = String::from(
        "// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n#![allow(dead_code)]\n\n",
    );
    if let Some(service) = &catalog.service {
        out.push_str(&format!("pub const SERVICE: &str = \"{}\";\n", rust_escape(service)));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "pub const {}: &str = \"{}\";\n",
            flag.rust_const,
            rust_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "pub const {}_DEFAULT: &str = \"{}\";\n",
                flag.rust_const,
                rust_escape(default)
            ));
        }
    }
    out.push('\n');
    out.push_str("/// Compile-time env key names from `.cli-flags.toml`.\n");
    out.push_str(&format!("pub struct {type_name} {{\n"));
    for flag in &catalog.flags {
        if let Some(help) = &flag.help {
            out.push_str(&format!("    /// {}\n", help.replace('\n', " ")));
        }
        out.push_str(&format!("    pub {}: &'static str,\n", flag.snake));
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl {type_name} {{\n    pub const KEYS: Self = Self {{\n"));
    for flag in &catalog.flags {
        out.push_str(&format!("        {}: {},\n", flag.snake, flag.rust_const));
    }
    out.push_str("    };\n}\n");
    out
}

fn rust_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn rust_emits_service_and_bind_consts() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("pub const SERVICE: &str = \"vxl-sidecar\";"));
        assert!(source.contains("pub const BIND: &str = \"VXL_SIDECAR_BIND\";"));
        assert!(source.contains("pub const BIND_DEFAULT: &str = \"127.0.0.1:9090\";"));
        assert!(source.contains("pub struct SidecarEnv"));
        assert!(source.contains("bind: BIND"));
    }
}
