#![forbid(unsafe_code)]

use crate::catalog::{to_pascal, Catalog};

pub fn render(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let mut out = String::from(
        "// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n#![allow(dead_code)]\n\n",
    );
    if let Some(service) = &catalog.service {
        out.push_str(&format!("pub const SERVICE: &str = \"{}\";\n", rust_escape(service)));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "pub const {}: &str = \"{}\";\n",
            flag.rust_const,
            rust_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "pub const {}_DEFAULT: &str = \"{}\";\n",
                flag.rust_const,
                rust_escape(default)
            ));
        }
    }
    out.push('\n');
    out.push_str("/// Compile-time env key names from `.cli-flags.toml`.\n");
    out.push_str(&format!("pub struct {type_name} {{\n"));
    for flag in &catalog.flags {
        if let Some(help) = &flag.help {
            out.push_str(&format!("    /// {}\n", help.replace('\n', " ")));
        }
        out.push_str(&format!("    pub {}: &'static str,\n", flag.snake));
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl {type_name} {{\n    pub const KEYS: Self = Self {{\n"));
    for flag in &catalog.flags {
        out.push_str(&format!("        {}: {},\n", flag.snake, flag.rust_const));
    }
    out.push_str("    };\n}\n");
    out
}

pub fn render_runtime(catalog: &Catalog) -> String {
    let type_name = to_pascal(&catalog.type_name);
    let values = format!("{type_name}Values");
    let mut out = String::from(
        "// Generated by flags-2-env from .cli-flags.toml. Do not edit.\n#![allow(dead_code)]\n\n",
    );
    out.push_str("/// Runtime values read from a lookup of env keys.\n");
    out.push_str(&format!("#[derive(Clone, Debug, PartialEq)]\npub struct {values} {{\n"));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "    pub {}: {},\n",
            flag.snake,
            rust_owned_type(&flag.flag_type, flag.default.is_some())
        ));
    }
    out.push_str("}\n\n");
    out.push_str("/// Pure: resolve values from an explicit lookup.\n");
    out.push_str(&format!(
        "pub fn load_from(lookup: impl Fn(&str) -> Option<String>) -> {values} {{\n    {values} {{\n"
    ));
    for flag in &catalog.flags {
        out.push_str(&format!(
            "        {}: {},\n",
            flag.snake,
            rust_load_expr(flag)
        ));
    }
    out.push_str("    }\n}\n\n");
    out.push_str("/// Effectful: read the process environment.\n");
    out.push_str(&format!(
        "pub fn load_from_os() -> {values} {{\n    load_from(|key| std::env::var(key).ok())\n}}\n"
    ));
    out.push_str(RUST_RUNTIME_HELPERS);
    out
}

fn rust_owned_type(flag_type: &str, has_default: bool) -> String {
    let inner = match flag_type {
        "bool" => "bool",
        "int" => "i64",
        "float" => "f64",
        _ => "String",
    };
    if has_default {
        inner.to_string()
    } else {
        format!("Option<{inner}>")
    }
}

fn rust_load_expr(flag: &crate::catalog::FlagSpec) -> String {
    let key = format!("\"{}\"", rust_escape(&flag.env));
    match (flag.flag_type.as_str(), flag.default.as_deref()) {
        ("bool", Some(default)) => format!(
            "parse_bool(lookup({key}), {})",
            default == "true" || default == "1"
        ),
        ("bool", None) => format!("lookup({key}).map(|raw| parse_bool(Some(raw), false))"),
        ("int", Some(default)) => format!(
            "parse_int(lookup({key}), {})",
            default.parse::<i64>().unwrap_or(0)
        ),
        ("int", None) => format!("lookup({key}).and_then(|raw| raw.parse().ok())"),
        ("float", Some(default)) => format!(
            "parse_float(lookup({key}), {})",
            default.parse::<f64>().unwrap_or(0.0)
        ),
        ("float", None) => format!("lookup({key}).and_then(|raw| raw.parse().ok())"),
        (_, Some(default)) => format!(
            "lookup({key}).filter(|value| !value.is_empty()).unwrap_or_else(|| \"{}\".to_string())",
            rust_escape(default)
        ),
        (_, None) => format!("lookup({key}).filter(|value| !value.is_empty())"),
    }
}

const RUST_RUNTIME_HELPERS: &str = r#"
fn parse_bool(raw: Option<String>, default: bool) -> bool {
    match raw.as_deref().map(str::trim) {
        Some("1" | "true" | "TRUE" | "yes" | "YES") => true,
        Some("0" | "false" | "FALSE" | "no" | "NO") => false,
        Some(_) | None => default,
    }
}

fn parse_int(raw: Option<String>, default: i64) -> i64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

fn parse_float(raw: Option<String>, default: f64) -> f64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}
"#;

fn rust_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn rust_emits_service_and_bind_consts() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("pub const SERVICE: &str = \"vxl-sidecar\";"));
        assert!(source.contains("pub const BIND: &str = \"VXL_SIDECAR_BIND\";"));
        assert!(source.contains("pub const BIND_DEFAULT: &str = \"127.0.0.1:9090\";"));
        assert!(source.contains("pub struct SidecarEnv"));
        assert!(source.contains("bind: BIND"));
    }

    #[test]
    fn rust_runtime_reads_bind_from_lookup() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = super::render_runtime(&catalog);
        assert!(source.contains("pub struct SidecarEnvValues"));
        assert!(source.contains("pub fn load_from"));
        assert!(source.contains("pub fn load_from_os"));
        assert!(source.contains("lookup(\"VXL_SIDECAR_BIND\")"));
    }
}
