#![forbid(unsafe_code)]

use crate::catalog::Catalog;

pub fn render(catalog: &Catalog) -> String {
    let mut out =
        String::from("/* Generated by flags-2-env from .cli-flags.toml. Do not edit. */\n\n");
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "export const SERVICE = \"{}\" as const;\n",
            ts_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "export const {} = \"{}\" as const;\n",
            flag.rust_const,
            ts_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "export const {}_DEFAULT = \"{}\" as const;\n",
                flag.rust_const,
                ts_escape(default)
            ));
        }
    }
    out.push('\n');
    out.push_str(&format!(
        "export interface {} {{\n",
        catalog.type_name
    ));
    for flag in &catalog.flags {
        let optional = if flag.default.is_some() { "" } else { "?" };
        out.push_str(&format!(
            "  readonly {}{}: {};\n",
            flag.env,
            optional,
            ts_value_type(&flag.flag_type)
        ));
    }
    out.push_str("}\n\nexport const EnvKeys = {\n");
    for flag in &catalog.flags {
        out.push_str(&format!("  {}: {},\n", flag.rust_const, flag.rust_const));
    }
    out.push_str("} as const;\n");
    out
}

fn ts_value_type(flag_type: &str) -> &'static str {
    match flag_type {
        "bool" => "boolean",
        "int" | "float" => "number",
        "array" => "ReadonlyArray<unknown>",
        "map" | "json" => "Readonly<Record<string, unknown>>",
        _ => "string",
    }
}

fn ts_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn typescript_emits_consts_and_interface() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("export const SERVICE = \"vxl-sidecar\" as const;"));
        assert!(source.contains("export const BIND = \"VXL_SIDECAR_BIND\" as const;"));
        assert!(source.contains("export interface SidecarEnv"));
        assert!(source.contains("readonly VXL_SIDECAR_BIND: string;"));
    }
}
