#![forbid(unsafe_code)]

use crate::catalog::Catalog;

pub fn render(catalog: &Catalog) -> String {
    let mut out =
        String::from("/* Generated by flags-2-env from .cli-flags.toml. Do not edit. */\n\n");
    if let Some(service) = &catalog.service {
        out.push_str(&format!(
            "export const SERVICE = \"{}\" as const;\n",
            ts_escape(service)
        ));
    }
    for flag in &catalog.flags {
        out.push_str(&format!(
            "export const {} = \"{}\" as const;\n",
            flag.rust_const,
            ts_escape(&flag.env)
        ));
        if let Some(default) = &flag.default {
            out.push_str(&format!(
                "export const {}_DEFAULT = \"{}\" as const;\n",
                flag.rust_const,
                ts_escape(default)
            ));
        }
    }
    out.push('\n');
    out.push_str(&format!("export interface {} {{\n", catalog.type_name));
    for flag in &catalog.flags {
        let optional = if flag.default.is_some() { "" } else { "?" };
        out.push_str(&format!(
            "  readonly {}{}: {};\n",
            flag.env,
            optional,
            ts_value_type(&flag.flag_type)
        ));
    }
    out.push_str("}\n\nexport const EnvKeys = {\n");
    for flag in &catalog.flags {
        out.push_str(&format!("  {}: {},\n", flag.rust_const, flag.rust_const));
    }
    out.push_str("} as const;\n");
    out
}

pub fn render_runtime(catalog: &Catalog) -> String {
    let values = format!("{}Values", catalog.type_name);
    let mut out =
        String::from("/* Generated by flags-2-env from .cli-flags.toml. Do not edit. */\n\n");
    out.push_str(&format!("export interface {values} {{\n"));
    for flag in &catalog.flags {
        let optional = if flag.default.is_some() { "" } else { "?" };
        out.push_str(&format!(
            "  readonly {}{}: {};\n",
            flag.snake,
            optional,
            ts_value_type(&flag.flag_type)
        ));
    }
    out.push_str("}\n\n");
    out.push_str("/** Pure: resolve values from an explicit lookup. */\n");
    out.push_str(&format!(
        "export function loadFrom(lookup: (key: string) => string | undefined): {values} {{\n  return {{\n"
    ));
    for flag in &catalog.flags {
        out.push_str(&format!("    {}: {},\n", flag.snake, ts_load_expr(flag)));
    }
    out.push_str("  };\n}\n\n");
    out.push_str("/** Effectful: read the process environment. */\n");
    out.push_str(&format!(
        "export function loadFromOs(\n  env: Record<string, string | undefined> = typeof process !== \"undefined\" ? process.env : {{}},\n): {values} {{\n  return loadFrom((key) => env[key]);\n}}\n"
    ));
    out.push_str(TS_RUNTIME_HELPERS);
    out.push_str(&crate::generate::overlay::render_typescript(catalog));
    out.push_str(&render_try_load(&values, catalog));
    out
}

fn render_try_load(values: &str, catalog: &Catalog) -> String {
    let mut out = format!(
        "\n/** Like `loadFrom`, but throws when a required key is missing or empty. */\nexport function tryLoadFrom(lookup: (key: string) => string | undefined): {values} {{\n  const values = loadFrom(lookup);\n"
    );
    for flag in catalog
        .flags
        .iter()
        .filter(|flag| flag.required && flag.default.is_none())
    {
        out.push_str(&format!(
            "  if (values.{snake} === undefined) {{\n    throw new MissingEnvError({{ envKey: \"{env}\", expectedType: \"{ty}\", examples: {examples} }});\n  }}\n",
            snake = flag.snake,
            env = ts_escape(&flag.env),
            ty = flag.flag_type,
            examples = ts_try_examples(flag),
        ));
    }
    out.push_str("  return values;\n}\n\n");
    out.push_str(&format!(
        "export function tryLoadFromOs(\n  env: Record<string, string | undefined> = typeof process !== \"undefined\" ? process.env : {{}},\n): {values} {{\n  return tryLoadFrom((key) => env[key]);\n}}\n"
    ));
    out
}

fn ts_try_examples(flag: &crate::catalog::FlagSpec) -> String {
    format!(
        "[{}]",
        crate::catalog::example_values(flag)
            .iter()
            .map(|value| format!("\"{}\"", ts_escape(value)))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn ts_load_expr(flag: &crate::catalog::FlagSpec) -> String {
    let key = format!("\"{}\"", ts_escape(&flag.env));
    match (flag.flag_type.as_str(), flag.default.as_deref()) {
        ("bool", Some(default)) => format!(
            "parseBool(lookup({key}), {})",
            if default == "true" || default == "1" {
                "true"
            } else {
                "false"
            }
        ),
        ("bool", None) => format!(
            "(() => {{ const raw = lookup({key}); return raw === undefined ? undefined : parseBool(raw, false); }})()"
        ),
        ("int", Some(default)) => format!(
            "parseIntValue(lookup({key}), {})",
            default.parse::<i64>().unwrap_or(0)
        ),
        ("int", None) => format!("parseOptionalNumber(lookup({key}), true)"),
        ("float", Some(default)) => format!(
            "parseFloatValue(lookup({key}), {})",
            default.parse::<f64>().unwrap_or(0.0)
        ),
        ("float", None) => format!("parseOptionalNumber(lookup({key}), false)"),
        (_, Some(default)) => format!("nonEmpty(lookup({key})) ?? \"{}\"", ts_escape(default)),
        (_, None) => format!("nonEmpty(lookup({key}))"),
    }
}

const TS_RUNTIME_HELPERS: &str = r#"
function nonEmpty(raw: string | undefined): string | undefined {
  const value = raw?.trim();
  return value ? value : undefined;
}

function parseBool(raw: string | undefined, fallback: boolean): boolean {
  switch (raw?.trim()) {
    case "1":
    case "true":
    case "TRUE":
    case "yes":
    case "YES":
      return true;
    case "0":
    case "false":
    case "FALSE":
    case "no":
    case "NO":
      return false;
    default:
      return fallback;
  }
}

function parseIntValue(raw: string | undefined, fallback: number): number {
  const parsed = Number.parseInt(raw?.trim() ?? "", 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

function parseFloatValue(raw: string | undefined, fallback: number): number {
  const parsed = Number.parseFloat(raw?.trim() ?? "");
  return Number.isNaN(parsed) ? fallback : parsed;
}

function parseOptionalNumber(raw: string | undefined, asInt: boolean): number | undefined {
  const value = raw?.trim();
  if (!value) {
    return undefined;
  }
  const parsed = asInt ? Number.parseInt(value, 10) : Number.parseFloat(value);
  return Number.isNaN(parsed) ? undefined : parsed;
}
"#;

fn ts_value_type(flag_type: &str) -> &'static str {
    match flag_type {
        "bool" => "boolean",
        "int" | "float" => "number",
        "array" => "ReadonlyArray<unknown>",
        "map" | "json" => "Readonly<Record<string, unknown>>",
        _ => "string",
    }
}

fn ts_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::catalog::parse_catalog;

    #[test]
    fn typescript_emits_consts_and_interface() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = render(&catalog);
        assert!(source.contains("export const SERVICE = \"vxl-sidecar\" as const;"));
        assert!(source.contains("export const BIND = \"VXL_SIDECAR_BIND\" as const;"));
        assert!(source.contains("export interface SidecarEnv"));
        assert!(source.contains("readonly VXL_SIDECAR_BIND: string;"));
    }

    #[test]
    fn typescript_runtime_reads_bind_from_lookup() {
        let catalog = parse_catalog(
            r#"
[identity]
service = "vxl-sidecar"

[flags.bind]
env = "VXL_SIDECAR_BIND"
default = "127.0.0.1:9090"
"#,
            Some("SidecarEnv"),
        )
        .unwrap();
        let source = super::render_runtime(&catalog);
        assert!(source.contains("export interface SidecarEnvValues"));
        assert!(source.contains("export function loadFrom"));
        assert!(source.contains("export function loadFromOs"));
        assert!(source.contains("export function tryLoadFromOs"));
        assert!(source.contains("lookup(\"VXL_SIDECAR_BIND\")"));
        assert!(source.contains("this.name = \"MissingEnvError\""));
        assert!(source.contains("readonly envKey: string"));
        assert!(source.contains("isSafeDotenvPath"));
    }
}
