// Generated by flags-2-env from .cli-flags.toml. Do not edit.
#![allow(dead_code)]

pub const SERVICE: &str = "flags-2-env-cli";
pub const API_BASE: &str = "FLAGS_2_ENV_API_BASE";
pub const CONFIG: &str = "FLAGS_2_ENV_CONFIG";
pub const JSON: &str = "FLAGS_2_ENV_JSON";

/// Compile-time env key names from `.cli-flags.toml`.
pub struct CliEnv {
    /// API HTTP base URL
    pub api_base: &'static str,
    /// Path to TOML configuration
    pub config: &'static str,
    /// Emit JSON
    pub json: &'static str,
}

impl CliEnv {
    pub const KEYS: Self = Self {
        api_base: API_BASE,
        config: CONFIG,
        json: JSON,
    };
}

// Generated by flags-2-env from .cli-flags.toml. Do not edit.

/// Runtime values read from a lookup of env keys.
#[derive(Clone, PartialEq)]
pub struct CliEnvValues {
    pub api_base: Option<String>,
    pub config: Option<String>,
    pub json: Option<bool>,
}

impl std::fmt::Debug for CliEnvValues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CliEnvValues")
            .field("api_base", &self.api_base)
            .field("config", &self.config)
            .field("json", &self.json)
            .finish()
    }
}

/// Pure: resolve values from an explicit lookup.
pub fn load_from(lookup: impl Fn(&str) -> Option<String>) -> CliEnvValues {
    CliEnvValues {
        api_base: lookup("FLAGS_2_ENV_API_BASE").filter(|value| !value.is_empty()),
        config: lookup("FLAGS_2_ENV_CONFIG").filter(|value| !value.is_empty()),
        json: lookup("FLAGS_2_ENV_JSON").map(|raw| parse_bool(Some(raw), false)),
    }
}

/// Effectful: read the process environment.
pub fn load_from_os() -> CliEnvValues {
    load_from(|key| std::env::var(key).ok())
}

fn parse_bool(raw: Option<String>, default: bool) -> bool {
    match raw.as_deref().map(str::trim) {
        Some("1" | "true" | "TRUE" | "yes" | "YES") => true,
        Some("0" | "false" | "FALSE" | "no" | "NO") => false,
        Some(_) | None => default,
    }
}

fn parse_int(raw: Option<String>, default: i64) -> i64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

fn parse_float(raw: Option<String>, default: f64) -> f64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MissingEnv {
    pub name: &'static str,
    pub expected_type: &'static str,
    pub examples: &'static [&'static str],
}

impl std::fmt::Display for MissingEnv {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "missing required environment variable {}\n  expected type: {}\n  examples: {}", self.name, self.expected_type, self.examples.join(", "))
    }
}

impl std::error::Error for MissingEnv {}

fn nonempty(raw: Option<&str>) -> Option<String> {
    raw.map(str::trim).filter(|value| !value.is_empty()).map(str::to_string)
}

fn require_env(
    name: &'static str,
    expected_type: &'static str,
    examples: &'static [&'static str],
    value: Option<String>,
) -> Result<String, MissingEnv> {
    match nonempty(value.as_deref()) {
        Some(value) => Ok(value),
        None => Err(MissingEnv {
            name,
            expected_type,
            examples,
        }),
    }
}

fn pick(
    keys: &[&str],
    order: &[&str],
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
    default: Option<&str>,
) -> Option<String> {
    for source in order {
        let map = match *source {
            "flags" => flags,
            "env_file" => dotenv,
            _ => shell,
        };
        for key in keys {
            if let Some(value) = nonempty(map.get(*key).map(String::as_str)) {
                return Some(value);
            }
        }
    }
    nonempty(default)
}

fn unquote(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2 {
        let bytes = trimmed.as_bytes();
        if (bytes[0] == b'"' && bytes[trimmed.len() - 1] == b'"')
            || (bytes[0] == b'\'' && bytes[trimmed.len() - 1] == b'\'')
        {
            return trimmed[1..trimmed.len() - 1].to_string();
        }
    }
    trimmed.to_string()
}

fn parse_dotenv(text: &str) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").map(str::trim).unwrap_or(line);
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if !is_dotenv_key(key) {
            continue;
        }
        out.insert(key.to_string(), unquote(value));
    }
    out
}

fn is_dotenv_key(key: &str) -> bool {
    let mut chars = key.chars();
    match chars.next() {
        Some(first) if first.is_ascii_alphabetic() || first == '_' => {
            chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
        }
        _ => false,
    }
}

fn is_safe_dotenv_path(path: &str) -> bool {
    if path.is_empty() || path.contains('\0') {
        return false;
    }
    let parsed = std::path::Path::new(path);
    if parsed.is_absolute() {
        return false;
    }
    if parsed
        .components()
        .any(|component| matches!(component, std::path::Component::ParentDir))
    {
        return false;
    }
    matches!(
        parsed.file_name().and_then(|name| name.to_str()),
        Some(name) if name == ".env" || name.starts_with(".env.")
    )
}

fn dotenv_enabled() -> bool {
    match std::env::var("FLAGS2ENV_DOTENV") {
        Ok(value) if matches!(value.trim(), "0" | "false" | "FALSE" | "no" | "NO") => false,
        _ => true,
    }
}

fn load_dotenv_files(files: &[&str]) -> std::collections::BTreeMap<String, String> {
    if !dotenv_enabled() {
        return std::collections::BTreeMap::new();
    }
    files.iter().filter(|path| is_safe_dotenv_path(path)).fold(
        std::collections::BTreeMap::new(),
        |mut acc, path| {
            if let Ok(text) = std::fs::read_to_string(path) {
                acc.extend(parse_dotenv(&text));
            }
            acc
        },
    )
}

fn shell_env() -> std::collections::BTreeMap<String, String> {
    std::env::vars().collect()
}

/// Resolve env-key -> value. Empty values fall through to the next source.
pub fn load_env_map(
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
) -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    let mut out = std::collections::BTreeMap::new();
    let api_base = pick(&["FLAGS_2_ENV_API_BASE"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = api_base {
        out.insert("FLAGS_2_ENV_API_BASE".to_string(), value);
    }
    let config = pick(&["FLAGS_2_ENV_CONFIG"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = config {
        out.insert("FLAGS_2_ENV_CONFIG".to_string(), value);
    }
    let json = pick(&["FLAGS_2_ENV_JSON"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = json {
        out.insert("FLAGS_2_ENV_JSON".to_string(), value);
    }
    match check_os_env(&out) {
        Ok(()) => Ok(out),
        Err(errors) => Err(contract_error_to_missing(&errors[0])),
    }
}

/// Effectful overlay: `.env` files then the process environment, ranked per key.
pub fn load_env_map_from_os() -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    load_env_map(&shell_env(), &load_dotenv_files(&[".env"]), &std::collections::BTreeMap::new())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContractError {
    pub path: String,
    pub message: String,
}

impl std::fmt::Display for ContractError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.path, self.message)
    }
}

/// Validate the resolved env map against the generated JSON Schema rules.
/// Call this at runtime (after overlay), not only at compile time.
pub fn check_os_env(
    env: &std::collections::BTreeMap<String, String>,
) -> Result<(), Vec<ContractError>> {
    let mut errors = Vec::new();
    if let Some(raw) = env.get("FLAGS_2_ENV_API_BASE").map(|value| value.trim()).filter(|value| !value.is_empty()) {
        if let Some(message) = contract_check_string(raw) {
            errors.push(ContractError { path: "FLAGS_2_ENV_API_BASE".into(), message });
        }
    }
    if let Some(raw) = env.get("FLAGS_2_ENV_CONFIG").map(|value| value.trim()).filter(|value| !value.is_empty()) {
        if let Some(message) = contract_check_string(raw) {
            errors.push(ContractError { path: "FLAGS_2_ENV_CONFIG".into(), message });
        }
    }
    if let Some(raw) = env.get("FLAGS_2_ENV_JSON").map(|value| value.trim()).filter(|value| !value.is_empty()) {
        if let Some(message) = contract_check_bool(raw) {
            errors.push(ContractError { path: "FLAGS_2_ENV_JSON".into(), message });
        }
    }
    for key in env.keys() {
        if !KNOWN_ENV_KEYS.contains(&key.as_str()) {
            errors.push(ContractError {
                path: key.clone(),
                message: "additional property not in the env contract".into(),
            });
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

fn contract_error_to_missing(error: &ContractError) -> MissingEnv {
    match error.path.as_str() {
        "FLAGS_2_ENV_API_BASE" => MissingEnv { name: "FLAGS_2_ENV_API_BASE", expected_type: "string", examples: &["http://127.0.0.1:8080", "https://api.example.test"] },
        "FLAGS_2_ENV_CONFIG" => MissingEnv { name: "FLAGS_2_ENV_CONFIG", expected_type: "string", examples: &["example-value"] },
        "FLAGS_2_ENV_JSON" => MissingEnv { name: "FLAGS_2_ENV_JSON", expected_type: "bool", examples: &["true", "false", "1", "0"] },
        _ => MissingEnv {
            name: "ENV_CONTRACT",
            expected_type: "json-schema-2020-12",
            examples: &[],
        },
    }
}

pub fn assert_os_env(env: &std::collections::BTreeMap<String, String>) {
    if let Err(errors) = check_os_env(env) {
        panic!(
            "environment contract violated: {}",
            errors
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("; ")
        );
    }
}

const KNOWN_ENV_KEYS: &[&str] = &["FLAGS_2_ENV_API_BASE", "FLAGS_2_ENV_CONFIG", "FLAGS_2_ENV_JSON", ];


fn contract_check_string(raw: &str) -> Option<String> {
    if raw.is_empty() {
        Some("empty string".into())
    } else {
        None
    }
}

fn contract_check_bool(raw: &str) -> Option<String> {
    match raw {
        "0" | "1" | "true" | "false" | "TRUE" | "FALSE" | "yes" | "no" | "YES" | "NO" => None,
        _ => Some(format!("not a bool env token: {raw}")),
    }
}

fn contract_check_int(raw: &str) -> Option<String> {
    raw.parse::<i64>().err().map(|err| err.to_string())
}

fn contract_check_float(raw: &str) -> Option<String> {
    raw.parse::<f64>().err().map(|err| err.to_string())
}

fn contract_check_json(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if (trimmed.starts_with('{') && trimmed.ends_with('}'))
        || (trimmed.starts_with('[') && trimmed.ends_with(']'))
    {
        None
    } else {
        Some("expected JSON object or array string".into())
    }
}

pub const OS_ENV_SCHEMA_JSON: &str = "{\n  \"$id\": \"https://github.com/flags-2-env/flags-2-env-cli/generated/json-schema/flags-2-env-cli/env.os.schema.json\",\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"additionalProperties\": false,\n  \"description\": \"Resolved environment map for CliEnv after flags-2-env overlay (flags > env_shell > env_file unless reordered). Values are still strings, as the OS stores them. Validate this object at runtime with `check_os_env` or `f2e check-contract`; do not hand-edit generated sources.\",\n  \"properties\": {\n    \"FLAGS_2_ENV_API_BASE\": {\n      \"description\": \"API HTTP base URL\",\n      \"examples\": [\n        \"http://127.0.0.1:8080\",\n        \"https://api.example.test\"\n      ],\n      \"minLength\": 1,\n      \"type\": \"string\",\n      \"x-env-key\": \"FLAGS_2_ENV_API_BASE\",\n      \"x-flag-type\": \"string\"\n    },\n    \"FLAGS_2_ENV_CONFIG\": {\n      \"description\": \"Path to TOML configuration\",\n      \"examples\": [\n        \"example-value\"\n      ],\n      \"minLength\": 1,\n      \"type\": \"string\",\n      \"x-env-key\": \"FLAGS_2_ENV_CONFIG\",\n      \"x-flag-type\": \"string\"\n    },\n    \"FLAGS_2_ENV_JSON\": {\n      \"description\": \"Emit JSON\",\n      \"enum\": [\n        \"0\",\n        \"1\",\n        \"true\",\n        \"false\",\n        \"TRUE\",\n        \"FALSE\",\n        \"yes\",\n        \"no\",\n        \"YES\",\n        \"NO\"\n      ],\n      \"examples\": [\n        \"true\",\n        \"false\",\n        \"1\",\n        \"0\"\n      ],\n      \"minLength\": 1,\n      \"type\": \"string\",\n      \"x-env-key\": \"FLAGS_2_ENV_JSON\",\n      \"x-flag-type\": \"bool\"\n    }\n  },\n  \"title\": \"CliEnv resolved environment\",\n  \"type\": \"object\",\n  \"x-flags-2-env\": {\n    \"generator\": \"flags-2-env\",\n    \"service\": \"flags-2-env-cli\",\n    \"typeName\": \"CliEnv\"\n  }\n}\n";
pub const VALUES_SCHEMA_JSON: &str = "{\n  \"$id\": \"https://github.com/flags-2-env/flags-2-env-cli/generated/json-schema/flags-2-env-cli/env.values.schema.json\",\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"additionalProperties\": false,\n  \"description\": \"Parsed flags-2-env values for CliEnv. extra properties are forbidden.\",\n  \"properties\": {\n    \"api_base\": {\n      \"anyOf\": [\n        {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        {\n          \"type\": \"null\"\n        }\n      ]\n    },\n    \"config\": {\n      \"anyOf\": [\n        {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        {\n          \"type\": \"null\"\n        }\n      ]\n    },\n    \"json\": {\n      \"anyOf\": [\n        {\n          \"type\": \"boolean\"\n        },\n        {\n          \"type\": \"null\"\n        }\n      ]\n    }\n  },\n  \"title\": \"CliEnvValues\",\n  \"type\": \"object\",\n  \"x-flags-2-env\": {\n    \"generator\": \"flags-2-env\",\n    \"service\": \"flags-2-env-cli\",\n    \"typeName\": \"CliEnv\"\n  }\n}\n";

/// Like `load_from`, but errors when a required key is missing or empty.
pub fn try_load_from(lookup: impl Fn(&str) -> Option<String>) -> Result<CliEnvValues, MissingEnv> {
    let values = load_from(lookup);
    Ok(values)
}

/// Effectful: read the process environment, erroring on missing required keys.
pub fn try_load_from_os() -> Result<CliEnvValues, MissingEnv> {
    try_load_from(|key| std::env::var(key).ok())
}
