/* Generated by flags-2-env from .cli-flags.toml. Do not edit. */

export const SERVICE = "flags-2-env-cli" as const;
export const API_BASE = "FLAGS_2_ENV_API_BASE" as const;
export const CONFIG = "FLAGS_2_ENV_CONFIG" as const;
export const JSON = "FLAGS_2_ENV_JSON" as const;

export interface CliEnv {
  readonly FLAGS_2_ENV_API_BASE?: string;
  readonly FLAGS_2_ENV_CONFIG?: string;
  readonly FLAGS_2_ENV_JSON?: boolean;
}

export const EnvKeys = {
  API_BASE: API_BASE,
  CONFIG: CONFIG,
  JSON: JSON,
} as const;

/* Generated by flags-2-env from .cli-flags.toml. Do not edit. */

export interface CliEnvValues {
  readonly api_base?: string;
  readonly config?: string;
  readonly json?: boolean;
}

/** Pure: resolve values from an explicit lookup. */
export function loadFrom(lookup: (key: string) => string | undefined): CliEnvValues {
  return {
    api_base: nonEmpty(lookup("FLAGS_2_ENV_API_BASE")),
    config: nonEmpty(lookup("FLAGS_2_ENV_CONFIG")),
    json: (() => { const raw = lookup("FLAGS_2_ENV_JSON"); return raw === undefined ? undefined : parseBool(raw, false); })(),
  };
}

/** Effectful: read the process environment. */
export function loadFromOs(
  env: Record<string, string | undefined> = typeof process !== "undefined" ? process.env : {},
): CliEnvValues {
  return loadFrom((key) => env[key]);
}

function nonEmpty(raw: string | undefined): string | undefined {
  const value = raw?.trim();
  return value ? value : undefined;
}

function parseBool(raw: string | undefined, fallback: boolean): boolean {
  switch (raw?.trim()) {
    case "1":
    case "true":
    case "TRUE":
    case "yes":
    case "YES":
      return true;
    case "0":
    case "false":
    case "FALSE":
    case "no":
    case "NO":
      return false;
    default:
      return fallback;
  }
}

function parseIntValue(raw: string | undefined, fallback: number): number {
  const parsed = Number.parseInt(raw?.trim() ?? "", 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

function parseFloatValue(raw: string | undefined, fallback: number): number {
  const parsed = Number.parseFloat(raw?.trim() ?? "");
  return Number.isNaN(parsed) ? fallback : parsed;
}

function parseOptionalNumber(raw: string | undefined, asInt: boolean): number | undefined {
  const value = raw?.trim();
  if (!value) {
    return undefined;
  }
  const parsed = asInt ? Number.parseInt(value, 10) : Number.parseFloat(value);
  return Number.isNaN(parsed) ? undefined : parsed;
}

function nonempty(raw: string | undefined): string | undefined {
  const value = raw?.trim();
  return value ? value : undefined;
}

export function requireEnv(
  name: string,
  expectedType: string,
  examples: readonly string[],
  value: string | undefined,
): string {
  const trimmed = nonempty(value);
  if (trimmed) {
    return trimmed;
  }
  throw new MissingEnvError({ envKey: name, expectedType, examples });
}

function pick(
  keys: readonly string[],
  order: readonly string[],
  shell: Record<string, string | undefined>,
  dotenv: Record<string, string | undefined>,
  flags: Record<string, string | undefined>,
  fallback: string | undefined,
): string | undefined {
  for (const source of order) {
    const map = source === "flags" ? flags : source === "env_file" ? dotenv : shell;
    for (const key of keys) {
      const value = nonempty(map[key]);
      if (value !== undefined) {
        return value;
      }
    }
  }
  return nonempty(fallback);
}

function unquote(value: string): string {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith("\"") && trimmed.endsWith("\"")) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

export function parseDotenv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const body = line.startsWith("export ") ? line.slice("export ".length).trim() : line;
    const eq = body.indexOf("=");
    if (eq <= 0) {
      continue;
    }
    const key = body.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      continue;
    }
    out[key] = unquote(body.slice(eq + 1));
  }
  return out;
}

function dotenvEnabled(): boolean {
  const value = typeof process !== "undefined" ? process.env.FLAGS2ENV_DOTENV : undefined;
  return !["0", "false", "FALSE", "no", "NO"].includes(value?.trim() ?? "");
}

function isSafeDotenvPath(path: string): boolean {
  if (!path || path.includes("\0") || path.includes("..")) {
    return false;
  }
  if (path.startsWith("/") || /^[A-Za-z]:[\\/]/.test(path)) {
    return false;
  }
  const base = path.split(/[\\/]/).pop() ?? "";
  return base === ".env" || base.startsWith(".env.");
}

export function loadDotenvFiles(files: readonly string[]): Record<string, string> {
  if (!dotenvEnabled() || typeof process === "undefined") {
    return {};
  }
  let fs: { readFileSync: (path: string, encoding: string) => string } | undefined;
  try {
    fs = require("fs") as { readFileSync: (path: string, encoding: string) => string };
  } catch {
    return {};
  }
  return files.filter(isSafeDotenvPath).reduce<Record<string, string>>((acc, path) => {
    try {
      return { ...acc, ...parseDotenv(fs!.readFileSync(path, "utf8")) };
    } catch {
      return acc;
    }
  }, {});
}
export interface MissingEnv {
  readonly envKey: string;
  readonly expectedType: string;
  readonly examples: readonly string[];
}

export class MissingEnvError extends Error implements MissingEnv {
  readonly envKey: string;
  readonly expectedType: string;
  readonly examples: readonly string[];
  constructor(fields: MissingEnv) {
    super(`missing required environment variable ${fields.envKey}\n  expected type: ${fields.expectedType}\n  examples: ${fields.examples.join(", ")}`);
    this.name = "MissingEnvError";
    this.envKey = fields.envKey;
    this.expectedType = fields.expectedType;
    this.examples = fields.examples;
  }
}

/** Resolve env-key -> value. Empty values fall through to the next source. */
export function loadEnvMap(
  shell: Record<string, string | undefined>,
  dotenv: Record<string, string | undefined>,
  flags: Record<string, string | undefined> = {},
): Record<string, string> {
  const out: Record<string, string> = {};
  const api_base = pick(["FLAGS_2_ENV_API_BASE"], ["flags", "env_shell", "env_file"], shell, dotenv, flags, undefined);
  if (api_base !== undefined) out["FLAGS_2_ENV_API_BASE"] = api_base;
  const config = pick(["FLAGS_2_ENV_CONFIG"], ["flags", "env_shell", "env_file"], shell, dotenv, flags, undefined);
  if (config !== undefined) out["FLAGS_2_ENV_CONFIG"] = config;
  const json = pick(["FLAGS_2_ENV_JSON"], ["flags", "env_shell", "env_file"], shell, dotenv, flags, undefined);
  if (json !== undefined) out["FLAGS_2_ENV_JSON"] = json;
  const contract = checkOsEnv(out);
  if (contract.length > 0) {
    const first = contract[0];
    throw new MissingEnvError({ envKey: first.path, expectedType: "json-schema-2020-12", examples: [] });
  }
  return out;
}

const DOTENV_FILES: readonly string[] = [".env"];
/** Effectful overlay: `.env` files then `process.env`, ranked per key. */
export function loadEnvMapFromOs(
  shell: Record<string, string | undefined> = typeof process !== "undefined" ? process.env : {},
): Record<string, string> {
  return loadEnvMap(shell, loadDotenvFiles(DOTENV_FILES), {});
}

export interface ContractError {
  readonly path: string;
  readonly message: string;
}

/** Validate the resolved env map against the generated JSON Schema rules. */
export function checkOsEnv(env: Record<string, string>): ContractError[] {
  const errors: ContractError[] = [];
  {
    const raw = nonEmpty(env["FLAGS_2_ENV_API_BASE"]);
    if (raw !== undefined) {
      const message = contractCheckString(raw);
      if (message) errors.push({ path: "FLAGS_2_ENV_API_BASE", message });
    }
  }
  {
    const raw = nonEmpty(env["FLAGS_2_ENV_CONFIG"]);
    if (raw !== undefined) {
      const message = contractCheckString(raw);
      if (message) errors.push({ path: "FLAGS_2_ENV_CONFIG", message });
    }
  }
  {
    const raw = nonEmpty(env["FLAGS_2_ENV_JSON"]);
    if (raw !== undefined) {
      const message = contractCheckBool(raw);
      if (message) errors.push({ path: "FLAGS_2_ENV_JSON", message });
    }
  }
  for (const key of Object.keys(env)) {
    if (!KNOWN_ENV_KEYS.includes(key)) {
      errors.push({ path: key, message: "additional property not in the env contract" });
    }
  }
  return errors;
}

export function assertOsEnv(env: Record<string, string>): void {
  const errors = checkOsEnv(env);
  if (errors.length > 0) {
    throw new Error(`environment contract violated: ${errors.map((error) => `${error.path}: ${error.message}`).join("; ")}`);
  }
}

const KNOWN_ENV_KEYS: readonly string[] = ["FLAGS_2_ENV_API_BASE", "FLAGS_2_ENV_CONFIG", "FLAGS_2_ENV_JSON", ];

function contractCheckString(raw: string): string | undefined {
  return raw.length === 0 ? "empty string" : undefined;
}
function contractCheckBool(raw: string): string | undefined {
  switch (raw) {
    case "0":
    case "1":
    case "true":
    case "false":
    case "TRUE":
    case "FALSE":
    case "yes":
    case "no":
    case "YES":
    case "NO":
      return undefined;
    default:
      return `not a bool env token: ${raw}`;
  }
}
function contractCheckInt(raw: string): string | undefined {
  return /^-?[0-9]+$/.test(raw) ? undefined : `not an int: ${raw}`;
}
function contractCheckFloat(raw: string): string | undefined {
  return Number.isNaN(Number.parseFloat(raw)) ? `not a float: ${raw}` : undefined;
}
function contractCheckJson(raw: string): string | undefined {
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === "object") return undefined;
    return "expected JSON object or array string";
  } catch {
    return "expected JSON object or array string";
  }
}

export const OS_ENV_SCHEMA = {"$id":"https://github.com/flags-2-env/flags-2-env-cli/generated/json-schema/flags-2-env-cli/env.os.schema.json","$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"description":"Resolved environment map for CliEnv after flags-2-env overlay (flags > env_shell > env_file unless reordered). Values are still strings, as the OS stores them. Validate this object at runtime with `check_os_env` or `f2e check-contract`; do not hand-edit generated sources.","properties":{"FLAGS_2_ENV_API_BASE":{"description":"API HTTP base URL","examples":["http://127.0.0.1:8080","https://api.example.test"],"minLength":1,"type":"string","x-env-key":"FLAGS_2_ENV_API_BASE","x-flag-type":"string"},"FLAGS_2_ENV_CONFIG":{"description":"Path to TOML configuration","examples":["example-value"],"minLength":1,"type":"string","x-env-key":"FLAGS_2_ENV_CONFIG","x-flag-type":"string"},"FLAGS_2_ENV_JSON":{"description":"Emit JSON","enum":["0","1","true","false","TRUE","FALSE","yes","no","YES","NO"],"examples":["true","false","1","0"],"minLength":1,"type":"string","x-env-key":"FLAGS_2_ENV_JSON","x-flag-type":"bool"}},"title":"CliEnv resolved environment","type":"object","x-flags-2-env":{"generator":"flags-2-env","service":"flags-2-env-cli","typeName":"CliEnv"}} as const;

/** Like `loadFrom`, but throws when a required key is missing or empty. */
export function tryLoadFrom(lookup: (key: string) => string | undefined): CliEnvValues {
  const values = loadFrom(lookup);
  return values;
}

export function tryLoadFromOs(
  env: Record<string, string | undefined> = typeof process !== "undefined" ? process.env : {},
): CliEnvValues {
  return tryLoadFrom((key) => env[key]);
}

