// Generated by flags-2-env from .cli-flags.toml. Do not edit.
#![allow(dead_code)]

pub const SERVICE: &str = "flags-2-env-cli";
pub const API_BASE: &str = "FLAGS_2_ENV_API_BASE";
pub const CONFIG: &str = "FLAGS_2_ENV_CONFIG";
pub const JSON: &str = "FLAGS_2_ENV_JSON";

/// Compile-time env key names from `.cli-flags.toml`.
pub struct CliEnv {
    /// API HTTP base URL
    pub api_base: &'static str,
    /// Path to TOML configuration
    pub config: &'static str,
    /// Emit JSON
    pub json: &'static str,
}

impl CliEnv {
    pub const KEYS: Self = Self {
        api_base: API_BASE,
        config: CONFIG,
        json: JSON,
    };
}

// Generated by flags-2-env from .cli-flags.toml. Do not edit.

/// Runtime values read from a lookup of env keys.
#[derive(Clone, PartialEq)]
pub struct CliEnvValues {
    pub api_base: Option<String>,
    pub config: Option<String>,
    pub json: Option<bool>,
}

impl std::fmt::Debug for CliEnvValues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CliEnvValues")
            .field("api_base", &self.api_base)
            .field("config", &self.config)
            .field("json", &self.json)
            .finish()
    }
}

/// Pure: resolve values from an explicit lookup.
pub fn load_from(lookup: impl Fn(&str) -> Option<String>) -> CliEnvValues {
    CliEnvValues {
        api_base: lookup("FLAGS_2_ENV_API_BASE").filter(|value| !value.is_empty()),
        config: lookup("FLAGS_2_ENV_CONFIG").filter(|value| !value.is_empty()),
        json: lookup("FLAGS_2_ENV_JSON").map(|raw| parse_bool(Some(raw), false)),
    }
}

/// Effectful: read the process environment.
pub fn load_from_os() -> CliEnvValues {
    load_from(|key| std::env::var(key).ok())
}

fn parse_bool(raw: Option<String>, default: bool) -> bool {
    match raw.as_deref().map(str::trim) {
        Some("1" | "true" | "TRUE" | "yes" | "YES") => true,
        Some("0" | "false" | "FALSE" | "no" | "NO") => false,
        Some(_) | None => default,
    }
}

fn parse_int(raw: Option<String>, default: i64) -> i64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

fn parse_float(raw: Option<String>, default: f64) -> f64 {
    raw.and_then(|value| value.parse().ok()).unwrap_or(default)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MissingEnv {
    pub name: &'static str,
    pub expected_type: &'static str,
    pub examples: &'static [&'static str],
}

impl std::fmt::Display for MissingEnv {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "missing required environment variable {}\n  expected type: {}\n  examples: {}", self.name, self.expected_type, self.examples.join(", "))
    }
}

impl std::error::Error for MissingEnv {}

fn nonempty(raw: Option<&str>) -> Option<String> {
    raw.map(str::trim).filter(|value| !value.is_empty()).map(str::to_string)
}

fn require_env(
    name: &'static str,
    expected_type: &'static str,
    examples: &'static [&'static str],
    value: Option<String>,
) -> Result<String, MissingEnv> {
    match nonempty(value.as_deref()) {
        Some(value) => Ok(value),
        None => Err(MissingEnv {
            name,
            expected_type,
            examples,
        }),
    }
}

fn pick(
    keys: &[&str],
    order: &[&str],
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
    default: Option<&str>,
) -> Option<String> {
    for source in order {
        let map = match *source {
            "flags" => flags,
            "env_file" => dotenv,
            _ => shell,
        };
        for key in keys {
            if let Some(value) = nonempty(map.get(*key).map(String::as_str)) {
                return Some(value);
            }
        }
    }
    nonempty(default)
}

fn unquote(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2 {
        let bytes = trimmed.as_bytes();
        if (bytes[0] == b'"' && bytes[trimmed.len() - 1] == b'"')
            || (bytes[0] == b'\'' && bytes[trimmed.len() - 1] == b'\'')
        {
            return trimmed[1..trimmed.len() - 1].to_string();
        }
    }
    trimmed.to_string()
}

fn parse_dotenv(text: &str) -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").map(str::trim).unwrap_or(line);
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if !is_dotenv_key(key) {
            continue;
        }
        out.insert(key.to_string(), unquote(value));
    }
    out
}

fn is_dotenv_key(key: &str) -> bool {
    let mut chars = key.chars();
    match chars.next() {
        Some(first) if first.is_ascii_alphabetic() || first == '_' => {
            chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
        }
        _ => false,
    }
}

fn is_safe_dotenv_path(path: &str) -> bool {
    if path.is_empty() || path.contains('\0') {
        return false;
    }
    let parsed = std::path::Path::new(path);
    if parsed.is_absolute() {
        return false;
    }
    if parsed
        .components()
        .any(|component| matches!(component, std::path::Component::ParentDir))
    {
        return false;
    }
    matches!(
        parsed.file_name().and_then(|name| name.to_str()),
        Some(name) if name == ".env" || name.starts_with(".env.")
    )
}

fn dotenv_enabled() -> bool {
    match std::env::var("FLAGS2ENV_DOTENV") {
        Ok(value) if matches!(value.trim(), "0" | "false" | "FALSE" | "no" | "NO") => false,
        _ => true,
    }
}

fn load_dotenv_files(files: &[&str]) -> std::collections::BTreeMap<String, String> {
    if !dotenv_enabled() {
        return std::collections::BTreeMap::new();
    }
    files.iter().filter(|path| is_safe_dotenv_path(path)).fold(
        std::collections::BTreeMap::new(),
        |mut acc, path| {
            if let Ok(text) = std::fs::read_to_string(path) {
                acc.extend(parse_dotenv(&text));
            }
            acc
        },
    )
}

fn shell_env() -> std::collections::BTreeMap<String, String> {
    std::env::vars().collect()
}

/// Resolve env-key -> value. Empty values fall through to the next source.
pub fn load_env_map(
    shell: &std::collections::BTreeMap<String, String>,
    dotenv: &std::collections::BTreeMap<String, String>,
    flags: &std::collections::BTreeMap<String, String>,
) -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    let mut out = std::collections::BTreeMap::new();
    let api_base = pick(&["FLAGS_2_ENV_API_BASE"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = api_base {
        out.insert("FLAGS_2_ENV_API_BASE".to_string(), value);
    }
    let config = pick(&["FLAGS_2_ENV_CONFIG"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = config {
        out.insert("FLAGS_2_ENV_CONFIG".to_string(), value);
    }
    let json = pick(&["FLAGS_2_ENV_JSON"], &["flags", "env_shell", "env_file"], shell, dotenv, flags, None);
    if let Some(value) = json {
        out.insert("FLAGS_2_ENV_JSON".to_string(), value);
    }
    Ok(out)
}

/// Effectful overlay: `.env` files then the process environment, ranked per key.
pub fn load_env_map_from_os() -> Result<std::collections::BTreeMap<String, String>, MissingEnv> {
    load_env_map(&shell_env(), &load_dotenv_files(&[".env"]), &std::collections::BTreeMap::new())
}

/// Like `load_from`, but errors when a required key is missing or empty.
pub fn try_load_from(lookup: impl Fn(&str) -> Option<String>) -> Result<CliEnvValues, MissingEnv> {
    let values = load_from(lookup);
    Ok(values)
}

/// Effectful: read the process environment, erroring on missing required keys.
pub fn try_load_from_os() -> Result<CliEnvValues, MissingEnv> {
    try_load_from(|key| std::env::var(key).ok())
}
