#!/usr/bin/env python3
"""Apply generated/ README + gitignore exceptions across consumer repos."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

CODES = Path("/Users/alexandermills/codes")
SKIP_ROOTS = {
    "dd",
    "_agent_audit_20260828",
    "_agent_push_20260823",
    "_fp_harden",
    "_sops_rollout",
    "_sops_rollout_20260823",
    "_to_delete",
    "clones",
    "submodules",
    "libs",
}

FROZEN = r"""# `generated/` — frozen artifacts (read-only)

This tree is **generated**. Do not hand-edit adapters here.

Typical producers:

- [`flags-2-env`](https://github.com/flags-2-env/flags-2-env-cli) (`f2e generate`)
- [`api-docs` / `ridl`](https://github.com/oresoftware/api-docs)
- interface adapters from `schema/tables.json` (`node src/generate.mjs`)

## Read-only on disk

After generate, artifact files are `chmod a-w` (0444). Directories stay
writable so the generator can add files.

**Git does not store the Unix write bit** — only the executable bit
(100644 vs 100755). After `git clone` / `git checkout`, files come back
writable. Restore the policy with the generator (`f2e generate`,
`ridl generate`, `node src/generate.mjs`) or:

```sh
scripts/freeze-generated.sh
```

Do not `chmod u+w` and then commit a hand-edit. Change the source catalog
(`.cli-flags.toml`, route map, `schema/tables.json`) and regenerate.

## JSON Schema (the contract)

If `json-schema/` is present, those documents are JSON Schema 2020-12.
Compile-time types are generated from that catalog. Runtime
`check_os_env` / `checkOsEnv` / `validate()` must pass on real payloads,
not only on types that compile. Unit tests should feed **valid** and
**invalid** instances (missing required keys, wrong types, extra properties).

```sh
f2e check-contract --config .cli-flags.toml --json env.fixture.json
```

## Gitignored trees

If this folder is listed in `.gitignore`, artifacts stay local. Keep this
README tracked with:

```
generated/*
!generated/README.md
```

(Do not ignore the directory node itself as `generated/` — that prevents
the `!README.md` exception from working.)
"""

NOT_FROZEN = r"""# `generated/` — not frozen

This directory is named `generated` but it is **not** a flags-2-env /
api-docs / interfaces freeze tree. Files here may stay writable. They are
not `chmod a-w` by policy.

Typical cases: compiler/tool caches, Flutter/Xcode `.generated/`, Gradle
`build/`, or scratch output that is not a source-of-truth adapter.
"""

FROZEN_MARKERS = (
    "Generated by flags-2-env",
    "Generated by ridl",
    "DO NOT EDIT",
    "Do not edit by hand",
    "Do not hand-edit",
    "GENERATED — do not hand-edit",
    "generated and checked in",
    "machine-written outputs",
)

NOT_FROZEN_PATH_BITS = (
    "/.generated/",
    "/node_modules/",
    "/target/",
    "/.dart_tool/",
    "/build/",
    "/.gradle/",
)


def git_root(path: Path) -> Path | None:
    cur = path if path.is_dir() else path.parent
    while cur != cur.parent:
        if (cur / ".git").exists():
            return cur
        cur = cur.parent
    return None


def classify(gen: Path) -> str:
    posix = "/" + str(gen).replace("\\", "/") + "/"
    if any(bit in posix for bit in NOT_FROZEN_PATH_BITS):
        return "not-frozen"
    if gen.name != "generated":
        return "not-frozen"
    try:
        for child in gen.rglob("*"):
            if not child.is_file():
                continue
            if child.suffix.lower() not in {
                ".dart",
                ".rs",
                ".ts",
                ".json",
                ".md",
                ".html",
                ".gleam",
                ".swift",
                ".kt",
                ".go",
                ".py",
            }:
                continue
            try:
                text = child.read_text(encoding="utf-8", errors="ignore")[:4000]
            except OSError:
                continue
            if any(marker in text for marker in FROZEN_MARKERS):
                return "frozen"
            if child.name in {"env.dart", "env.rs", "env.ts", "api-docs.json"}:
                return "frozen"
    except OSError:
        pass
    # empty generated/ with only our future README: treat as frozen if parent
    # looks like a service repo
    parent = gen.parent.name
    if any(
        parent.endswith(s)
        for s in (
            "-cli",
            "-sidecar.rs",
            "-api-server.rs",
            "-web-server.rs",
            "-mcp-server.rs",
            "-interfaces",
            "-infra",
            "-flutter",
            "-desktop-app.rs",
            "-e2e",
        )
    ):
        return "frozen"
    return "not-frozen"


def ensure_gitignore_exception(repo: Path, gen: Path) -> bool:
    gi = repo / ".gitignore"
    if not gi.is_file():
        return False
    rel = gen.relative_to(repo).as_posix()
    text = gi.read_text(encoding="utf-8")
    patterns = {line.strip() for line in text.splitlines() if line.strip()}
    ignored_as_dir = {rel, rel + "/", f"/{rel}", f"/{rel}/", "generated/", "generated"}
    if not (patterns & ignored_as_dir) and "generated/" not in text:
        # check git check-ignore
        proc = subprocess.run(
            ["git", "check-ignore", "-q", f"{rel}/README.md"],
            cwd=repo,
            capture_output=True,
        )
        if proc.returncode != 0:
            return False
    block = f"\n# keep generated policy README in VCS even when artifacts are local\n{rel}/*\n!{rel}/README.md\n"
    if f"!{rel}/README.md" in text:
        return False
    # Replace a bare `generated/` ignore so the exception can work.
    lines = []
    changed = False
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped in {rel, rel + "/", "generated/", "generated"} and not stripped.startswith("!"):
            lines.append(f"{rel}/*\n")
            changed = True
            continue
        lines.append(line)
    new = "".join(lines)
    if f"!{rel}/README.md" not in new:
        if not new.endswith("\n"):
            new += "\n"
        new += block
        changed = True
    if changed:
        gi.write_text(new, encoding="utf-8")
    return changed


def existing_readme_policy(path: Path) -> str | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    if "not frozen" in text.lower() and "chmod" not in text.lower():
        return "not-frozen"
    if "frozen" in text.lower() or "do not hand-edit" in text.lower():
        return "frozen"
    return "other"


def merge_frozen_readme(existing: str) -> str:
    if "Read-only on disk" in existing and "JSON Schema" in existing:
        return existing
    extra = "\n".join(
        [
            "",
            "## Read-only on disk",
            "",
            "Generated adapters are `chmod a-w` (0444) after the producer runs.",
            "Git does not store the Unix write bit; restore with the generator",
            "or `scripts/freeze-generated.sh`.",
            "",
            "## JSON Schema and runtime checks",
            "",
            "JSON Schema 2020-12 (when present under `json-schema/`) is the",
            "contract. Runtime `validate()` / `check_os_env` / `f2e check-contract`",
            "must pass on real payloads, not only at compile time. Unit tests",
            "should include valid and invalid instances.",
            "",
        ]
    )
    return existing.rstrip() + extra


REPOS = [
    ("flags-2-env", "flags-2-env-cli"),
    ("flags-2-env", "flags-2-env-sidecar.rs"),
    ("flags-2-env", "flags-2-env-clients"),
    ("flags-2-env", "flags-2-env-flutter"),
    ("flags-2-env", "flags-2-env-interfaces"),
    ("sonus-auris", "sonus-auris-cli"),
    ("sonus-auris", "sonus-auris-api-server.rs"),
    ("sonus-auris", "sonus-auris-interfaces"),
    ("sonus-auris", "sonus-auris-sidecar.rs"),
    ("fiducia-cloud", "fiducia-cli.rs"),
    ("fiducia-cloud", "fiducia-interfaces"),
    ("fiducia-cloud", "fiducia-infra"),
    ("fiducia-cloud", "fiducia-mcp-server.rs"),
    ("zed-pkg", "zed-cli"),
    ("opto-sync", "opto-sync-sidecar.rs"),
    ("shared-auth", "shared-auth-sidecar.rs"),
    ("shared-auth", "shared-auth-interfaces"),
    ("scintilla-run", "scintilla-api-server.rs"),
    ("canonical-cloud", "canonical-cli"),
    ("3FA-app", "3fa-cli"),
    ("daedalus-fab", "daedalus-cli"),
    ("daedalus-fab", "daedalus-interfaces"),
    ("athlet-o", "athleto-mcp-server.rs"),
    ("cliptown", "cliptown-cli"),
    ("declarative-migrations", "declmig-cli"),
    ("ecma-d", "ecmad-cli"),
    ("ores-otel", "ores-otel-cli"),
    ("hypesiege", "hypesiege-cli"),
    ("fanwaave", "fanwaave-cli"),
    ("StreemPilot", "sp-cli"),
    ("messaging-intel", "msgint-api-server.rs"),
    ("usa-acc", "usa-acc-cli"),
    ("akrion-sim", "akrion-web-server.rs"),
    ("benefactor-cc", "benefactor-cli"),
    ("oresoftware", "api-docs"),
]


def apply_repo(org: str, name: str) -> dict:
    repo = CODES / org / name
    result = {"org": org, "repo": name, "path": str(repo), "status": "skip", "reason": "", "files": []}
    if not repo.is_dir():
        result["reason"] = "missing"
        return result
    if not (repo / ".git").exists():
        result["reason"] = "not a git root"
        return result
    gens = []
    for path in repo.rglob("generated"):
        if not path.is_dir():
            continue
        posix = path.as_posix()
        if any(bit in posix for bit in ("/node_modules/", "/target/", "/.git/", "/.dart_tool/")):
            continue
        if path.name != "generated":
            continue
        gens.append(path)
    if not gens:
        # still add top-level generated/ if we want to document intent
        top = repo / "generated"
        if top.is_dir():
            gens.append(top)
    if not gens:
        result["reason"] = "no generated/"
        return result
    changed = []
    for gen in gens:
        kind = classify(gen)
        readme = gen / "README.md"
        policy = existing_readme_policy(readme)
        if kind == "frozen":
            if policy == "frozen" and readme.is_file() and "Read-only on disk" in readme.read_text(encoding="utf-8"):
                body = merge_frozen_readme(readme.read_text(encoding="utf-8"))
                if body != readme.read_text(encoding="utf-8"):
                    readme.write_text(body, encoding="utf-8")
                    changed.append(str(readme.relative_to(repo)))
            elif readme.is_file() and policy in {"frozen", "other"}:
                body = merge_frozen_readme(readme.read_text(encoding="utf-8"))
                if body != readme.read_text(encoding="utf-8"):
                    readme.write_text(body if body.endswith("\n") else body + "\n", encoding="utf-8")
                    changed.append(str(readme.relative_to(repo)))
            else:
                readme.parent.mkdir(parents=True, exist_ok=True)
                readme.write_text(FROZEN, encoding="utf-8")
                changed.append(str(readme.relative_to(repo)))
            if ensure_gitignore_exception(repo, gen):
                changed.append(".gitignore")
        else:
            if not readme.is_file():
                readme.parent.mkdir(parents=True, exist_ok=True)
                readme.write_text(NOT_FROZEN, encoding="utf-8")
                changed.append(str(readme.relative_to(repo)))
            elif "not frozen" not in readme.read_text(encoding="utf-8").lower():
                # don't overwrite a careful existing README with not-frozen
                pass
    freeze_script = repo / "scripts" / "freeze-generated.sh"
    src_script = CODES / "flags-2-env" / "flags-2-env-cli" / "scripts" / "freeze-generated.sh"
    if src_script.is_file() and any(classify(g) == "frozen" for g in gens):
        freeze_script.parent.mkdir(parents=True, exist_ok=True)
        text = src_script.read_text(encoding="utf-8")
        if not freeze_script.is_file() or freeze_script.read_text(encoding="utf-8") != text:
            freeze_script.write_text(text, encoding="utf-8")
            freeze_script.chmod(0o755)
            changed.append("scripts/freeze-generated.sh")
    changed = sorted(set(changed))
    if not changed:
        result["status"] = "unchanged"
        result["reason"] = "already documented"
        return result
    result["status"] = "changed"
    result["files"] = changed
    return result


def main() -> int:
    rows = [apply_repo(org, name) for org, name in REPOS]
    for row in rows:
        print(f"{row['status']:10} {row['org']}/{row['repo']}: {row.get('reason') or ', '.join(row['files'])}")
    changed = [row for row in rows if row["status"] == "changed"]
    print(f"\nchanged {len(changed)} / {len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
